### ISSUE TITLE
Scheduled Job Missing after Installation

### ISSUE THREAD

**Issue by mcollopy** [veda-consulting-company/uk.co.vedaconsulting.mautic#12] opened 2020-10-10 03:08 UTC
Hi there - awesome extension!  I've just installed it and followed the instructions but as per the subject line, the Scheduled Job wasn't there as may be expected from the instructions:
"Find the job Mautic Push Sync, and click edit. Check is this Scheduled Job active."

I created a job guessing the specifications were as follows:
API Entity: Mautic
API Action: pushsync
Paramaters: none

It seems to run but not sure whether this is right, or whether it is running in dry_run more - see attached screenshot of the results.
<img width="1440" alt="Screen Shot 2020-10-10 at 2 04 16 pm" src="https://user-images.githubusercontent.com/1475720/95644366-df0d5d80-0b01-11eb-9aca-310ca19e2edc.png">

I'd be grateful if you could please confirm whether I'm doing this correctly, and whether or not there's a few jobs that can be specified, parameters if required.

Thanks, Mick

**Comment by mcollopy** [comment] 2021-06-22 01:36
The job was added manually using settings:
api.mautic.pushsync
Mautic 
pushsync

I can get the job to run, although I have received this warning:

Warning: Invalid argument supplied for foreach() in civicrm_api3_mautic_Pushsync() (line 36 of sites/default/files/civicrm/ext/uk.co.vedaconsulting.mautic/api/v3/Mautic/Pushsync.php).

**Comment by veda-consulting** [comment] 2021-07-01 17:43
@mcollopy thanks for the feedback, we'll get someone onto it

**Comment by cmolava** [comment] 2021-07-07 19:15
@mcollopy It looks like you set up the Scheduled Job correctly. The log on the screenshot shows that the CiviCRM groups were mostly already synchronized with their connected Mautic Segments, except for one contact, which was updated.
The dry run label in the job log is misleading and will be fixed in the 1.4 release.

It's possible to set the parameter (dry_run=1) in the scheduled job settings, but if one wishes to see what the result of a push will be, it's more convenient to push to Mautic manually and check the dry run option.

I cannot reproduce the issue with the missing job after the extension is installed, so will assume it has been fixed since you reported it.

**Comment by mcollopy** [comment] 2021-07-07 22:47
Thanks @cmolava  - I assume I can ignore the "Warning: Invalid argument" as a non critical code bug which will be addressed in future releases.
Also "whether or not there's a few jobs that can be specified, parameters if required." - assume there are none, if none advised.
If no further udpates, the issue can be resolved, thanks.

**Comment by cmolava** [comment] 2021-07-08 11:04
Thanks @mcollopy. 
The invalid warning will be fixed in the 1.4 release.
Only a single push to Mautic job is expected to be scheduled, rather than multiple instances with different parameters.

**Closed by cmolava** 2021-07-08 11:04 UTC
Labels: bug
